insert into chapter_76 (HTS_code, left_mark, right_mark, Depth, Title) values ('76', 1, 74, 0,'Aluminium and articles thereof');
insert into chapter_76 (HTS_code, left_mark, right_mark, Depth, Title) values ('7609', 2, 9, 1,'Aluminium tube or pipe fittings (for example, couplings, elbows, sleeves)');
insert into chapter_76 (HTS_code, left_mark, right_mark, Depth, Title) values ('7616', 10, 73, 1,'Other articles of aluminium');
insert into chapter_76 (HTS_code, left_mark, right_mark, Depth, Title) values ('7609.00.0010', 3, 4, 2,'For use in certain types of aircraft');
insert into chapter_76 (HTS_code, left_mark, right_mark, Depth, Title) values ('7609.00.0020', 5, 6, 2,'Aluminium tube or pipe fittings for affixing to radiators of motor bikes');
insert into chapter_76 (HTS_code, left_mark, right_mark, Depth, Title) values ('7609.00.0090', 7, 8, 2,'Other');
insert into chapter_76 (HTS_code, left_mark, right_mark, Depth, Title) values ('7616.10.', 11, 20, 2,'Nails, tacks, staples (other than those of heading 8305), screws, bolts, nuts, screw hooks, rivets, cotters, cotter pins, washers and similar articles');
insert into chapter_76 (HTS_code, left_mark, right_mark, Depth, Title) values ('7616.9.', 21, 72, 2,'Other');
insert into chapter_76 (HTS_code, left_mark, right_mark, Depth, Title) values ('7616.10.0010', 12, 13, 3,'Self-locking bolts and nuts (of the type "Hi-lok")');
insert into chapter_76 (HTS_code, left_mark, right_mark, Depth, Title) values ('7616.10.009', 14, 19, 3,'Other');
insert into chapter_76 (HTS_code, left_mark, right_mark, Depth, Title) values ('7616.10.0091', 15, 16, 4,'For use in certain types of aircraft');
insert into chapter_76 (HTS_code, left_mark, right_mark, Depth, Title) values ('7616.10.0099', 17, 18, 4,'Other');
insert into chapter_76 (HTS_code, left_mark, right_mark, Depth, Title) values ('7616.91.0000', 22, 23, 3,'Cloth, grill, netting and fencing, of aluminium wire');
insert into chapter_76 (HTS_code, left_mark, right_mark, Depth, Title) values ('7616.99', 24, 71, 3,'Other');
insert into chapter_76 (HTS_code, left_mark, right_mark, Depth, Title) values ('7616.99.10', 25, 38, 4,'Cast');
insert into chapter_76 (HTS_code, left_mark, right_mark, Depth, Title) values ('7616.99.90', 39, 70, 4,'Other');
insert into chapter_76 (HTS_code, left_mark, right_mark, Depth, Title) values ('7616.99.1010', 26, 27, 5,'Collars, flanges and other devices for fixing, jointing, clamping or spacing, for use in certain types of aircraft');
insert into chapter_76 (HTS_code, left_mark, right_mark, Depth, Title) values ('7616.99.1020', 28, 29, 5,'"Quick change" apparatus for transforming passenger transport aeroplanes into goods transport aeroplanes and vice versa, for use in certain types of aircraft');
insert into chapter_76 (HTS_code, left_mark, right_mark, Depth, Title) values ('7616.99.1030', 30, 31, 5,'Aluminium engine bracket, with dimensions of: height of more than 10 mm but not more than 200 mm, width of more than 10 mm but not more than 200 mm, length of more than 10 mm but not more than 200 mm equipped with at least two fixing holes, made of aluminium alloys ENAC-46100 or ENAC-42100 (based on the norm EN:1706) with following characteristics: internal porosity not more than 1 mm; outer porosity not more than 2 mm; Rockwell hardness HRB 10 or more of a kind used in the production of suspensions systems for engines in motor vehicles');
insert into chapter_76 (HTS_code, left_mark, right_mark, Depth, Title) values ('7616.99.109', 32, 37, 5,'Other');
insert into chapter_76 (HTS_code, left_mark, right_mark, Depth, Title) values ('7616.99.1091', 33, 34, 6,'Aluminium radiators and elements or sections of which such radiator is composed, whether or not such elements are assembled in blocks');
insert into chapter_76 (HTS_code, left_mark, right_mark, Depth, Title) values ('7616.99.1099', 35, 36, 6,'Other');
insert into chapter_76 (HTS_code, left_mark, right_mark, Depth, Title) values ('7616.99.900', 40, 45, 5,'Hand-made');
insert into chapter_76 (HTS_code, left_mark, right_mark, Depth, Title) values ('7616.99.9001', 41, 42, 6,'Aluminium radiators and elements or sections of which such radiator is composed, whether or not such elements are assembled in blocks');
insert into chapter_76 (HTS_code, left_mark, right_mark, Depth, Title) values ('7616.99.9009', 43, 44, 6,'Other');
insert into chapter_76 (HTS_code, left_mark, right_mark, Depth, Title) values ('', 46, 69, 5,'Other');
insert into chapter_76 (HTS_code, left_mark, right_mark, Depth, Title) values ('7616.99.9010', 47, 48, 6,'Collars, flanges and other devices for fixing, jointing, clamping or spacing, for use in certain types of aircraft');
insert into chapter_76 (HTS_code, left_mark, right_mark, Depth, Title) values ('7616.99.9015', 49, 50, 6,'Honeycomb aluminium blocks of the type used in the manufacture of aircraft parts');
insert into chapter_76 (HTS_code, left_mark, right_mark, Depth, Title) values ('7616.99.9020', 51, 52, 6,'"Quick change" apparatus for transforming passenger transport aeroplanes into goods transport aeroplanes and vice versa, for use in certain types of aircraft');
insert into chapter_76 (HTS_code, left_mark, right_mark, Depth, Title) values ('7616.99.9025', 53, 54, 6,'Metallised film: consisting of eight or more layers of aluminium (CAS RN 7429-90-5) of a purity of 99,8 % or more, with an optical density of each aluminium layer of not more than 3.0, with each aluminium layer separated by a resin layer, on a carrier film of PET, and on rolls of up to 50 000 metres in lengt');
insert into chapter_76 (HTS_code, left_mark, right_mark, Depth, Title) values ('7616.99.9030', 55, 56, 6,'Plates and sheets of variable thickness of widths of 1 200 mm or more, for use in certain types of aircraft');
insert into chapter_76 (HTS_code, left_mark, right_mark, Depth, Title) values ('7616.99.9060', 57, 58, 6,'Disc (target) with deposition material, consisting of molybdenum silicide: containing 1mg/kg or less of sodium and mounted on a copper or aluminium suppor');
insert into chapter_76 (HTS_code, left_mark, right_mark, Depth, Title) values ('7616.99.9070', 59, 60, 6,'Connecting components for use in the production of helicopter tail rotor shafts');
insert into chapter_76 (HTS_code, left_mark, right_mark, Depth, Title) values ('7616.99.9077', 61, 62, 6,'Television pedestal stands with or without bracket for fixation to and stabilization of television cabinet case/body');
insert into chapter_76 (HTS_code, left_mark, right_mark, Depth, Title) values ('7616.99.909', 63, 68, 6,'Other');
insert into chapter_76 (HTS_code, left_mark, right_mark, Depth, Title) values ('7616.99.9091', 64, 65, 7,'Aluminium radiators and elements or sections of which such radiator is composed, whether or not such elements are assembled in blocks');
insert into chapter_76 (HTS_code, left_mark, right_mark, Depth, Title) values ('7616.99.9099', 66, 67, 7,'Other');
