#insert into chapter_73 (HTS_code, lft, rght, depth, title) values (73, 1, 217, 0,'Articles of iron or steel');
insert into chapter_73 (HTS_code, lft, rght, depth, title) values ('7307', 2, 216, 1,'Tube or pipe fittings (for example, couplings, elbows, sleeves), of iron or steel');
insert into chapter_73 (HTS_code, lft, rght, depth, title) values ('7307.1', 3, 24, 2,'Cast fittings');
insert into chapter_73 (HTS_code, lft, rght, depth, title) values ('7307.2', 25, 90, 2,'Other, of stainless steel');
insert into chapter_73 (HTS_code, lft, rght, depth, title) values ('7307.9', 91, 215, 2,'Other');
insert into chapter_73 (HTS_code, lft, rght, depth, title) values ('7307.11', 4, 9, 3,'Of non-malleable cast iron');
insert into chapter_73 (HTS_code, lft, rght, depth, title) values ('7307.19', 10, 23, 3,'Other');
insert into chapter_73 (HTS_code, lft, rght, depth, title) values ('7307.21', 26, 31, 3,'Flanges');
insert into chapter_73 (HTS_code, lft, rght, depth, title) values ('7307.22', 32, 45, 3,'Threaded elbows, bends and sleeves');
insert into chapter_73 (HTS_code, lft, rght, depth, title) values ('7307.23', 46, 76, 3,'Butt welding fittings');
insert into chapter_73 (HTS_code, lft, rght, depth, title) values ('7307.29', 76, 89, 3,'Other');
insert into chapter_73 (HTS_code, lft, rght, depth, title) values ('7307.91', 92, 97, 3,'Flanges');
insert into chapter_73 (HTS_code, lft, rght, depth, title) values ('7307.92', 98, 111, 3,'Threaded elbows, bends and sleeves');
insert into chapter_73 (HTS_code, lft, rght, depth, title) values ('7307.93', 112, 178, 3,'Butt welding fittings');
insert into chapter_73 (HTS_code, lft, rght, depth, title) values ('7307.99', 179, 214, 3,'Other');
insert into chapter_73 (HTS_code, lft, rght, depth, title) values ('7307.11.10', 5, 6, 4,'Of a kind used in pressure systems');
insert into chapter_73 (HTS_code, lft, rght, depth, title) values ('7307.11.90', 7, 8, 4,'Other');
insert into chapter_73 (HTS_code, lft, rght, depth, title) values ('7307.19.10', 11, 16, 4,'Of malleable cast iron');
insert into chapter_73 (HTS_code, lft, rght, depth, title) values ('7307.19.90', 17, 22, 4,'Other');
insert into chapter_73 (HTS_code, lft, rght, depth, title) values ('7307.19.1010', 12, 13, 5,'Threaded, excluding bodies of compression fittings using ISO DIN 13 metric thread and circular junction boxes without having a lid');
insert into chapter_73 (HTS_code, lft, rght, depth, title) values ('7307.19.1090', 14, 15, 5,'Other');
insert into chapter_73 (HTS_code, lft, rght, depth, title) values ('7307.19.9010', 18, 19, 5,'Threaded, of spheroidal graphite cast iron, excluding bodies of compression fittings using ISO DIN 13 metric thread');
insert into chapter_73 (HTS_code, lft, rght, depth, title) values ('7307.19.9090', 20, 21, 5,'Other');
insert into chapter_73 (HTS_code, lft, rght, depth, title) values ('7307.21.0010', 27, 28, 4,'For use in certain types of aircraft');
insert into chapter_73 (HTS_code, lft, rght, depth, title) values ('7307.21.0090', 29, 30, 4,'Other');
insert into chapter_73 (HTS_code, lft, rght, depth, title) values ('7307', 1, 217, 0,'Articles of iron or steel');
insert into chapter_73 (HTS_code, lft, rght, depth, title) values ('7307', 1, 217, 0,'Articles of iron or steel');
insert into chapter_73 (HTS_code, lft, rght, depth, title) values ('7307', 1, 217, 0,'Articles of iron or steel');
insert into chapter_73 (HTS_code, lft, rght, depth, title) values ('7307', 1, 217, 0,'Articles of iron or steel');
insert into chapter_73 (HTS_code, lft, rght, depth, title) values ('7307', 1, 217, 0,'Articles of iron or steel');
insert into chapter_73 (HTS_code, lft, rght, depth, title) values ('7307', 1, 217, 0,'Articles of iron or steel');
insert into chapter_73 (HTS_code, lft, rght, depth, title) values ('7307', 1, 217, 0,'Articles of iron or steel');
insert into chapter_73 (HTS_code, lft, rght, depth, title) values ('7307', 1, 217, 0,'Articles of iron or steel');
insert into chapter_73 (HTS_code, lft, rght, depth, title) values ('7307', 1, 217, 0,'Articles of iron or steel');
insert into chapter_73 (HTS_code, lft, rght, depth, title) values ('7307', 1, 217, 0,'Articles of iron or steel');
insert into chapter_73 (HTS_code, lft, rght, depth, title) values ('7307', 1, 217, 0,'Articles of iron or steel');
insert into chapter_73 (HTS_code, lft, rght, depth, title) values ('7307', 1, 217, 0,'Articles of iron or steel');
insert into chapter_73 (HTS_code, lft, rght, depth, title) values ('7307', 1, 217, 0,'Articles of iron or steel');
insert into chapter_73 (HTS_code, lft, rght, depth, title) values ('7307', 1, 217, 0,'Articles of iron or steel');
insert into chapter_73 (HTS_code, lft, rght, depth, title) values ('7307', 1, 217, 0,'Articles of iron or steel');
insert into chapter_73 (HTS_code, lft, rght, depth, title) values ('7307', 1, 217, 0,'Articles of iron or steel');
insert into chapter_73 (HTS_code, lft, rght, depth, title) values ('7307', 1, 217, 0,'Articles of iron or steel');
insert into chapter_73 (HTS_code, lft, rght, depth, title) values ('7307', 1, 217, 0,'Articles of iron or steel');
insert into chapter_73 (HTS_code, lft, rght, depth, title) values ('7307', 1, 217, 0,'Articles of iron or steel');
insert into chapter_73 (HTS_code, lft, rght, depth, title) values ('7307', 1, 217, 0,'Articles of iron or steel');
insert into chapter_73 (HTS_code, lft, rght, depth, title) values ('7307', 1, 217, 0,'Articles of iron or steel');
insert into chapter_73 (HTS_code, lft, rght, depth, title) values (73, 1, 217, 0,'Articles of iron or steel');
insert into chapter_73 (HTS_code, lft, rght, depth, title) values (73, 1, 217, 0,'Articles of iron or steel');
insert into chapter_73 (HTS_code, lft, rght, depth, title) values (73, 1, 217, 0,'Articles of iron or steel');
insert into chapter_73 (HTS_code, lft, rght, depth, title) values (73, 1, 217, 0,'Articles of iron or steel');
insert into chapter_73 (HTS_code, lft, rght, depth, title) values (73, 1, 217, 0,'Articles of iron or steel');
insert into chapter_73 (HTS_code, lft, rght, depth, title) values (73, 1, 217, 0,'Articles of iron or steel');
insert into chapter_73 (HTS_code, lft, rght, depth, title) values (73, 1, 217, 0,'Articles of iron or steel');
insert into chapter_73 (HTS_code, lft, rght, depth, title) values (73, 1, 217, 0,'Articles of iron or steel');
insert into chapter_73 (HTS_code, lft, rght, depth, title) values (73, 1, 217, 0,'Articles of iron or steel');
insert into chapter_73 (HTS_code, lft, rght, depth, title) values (73, 1, 217, 0,'Articles of iron or steel');
insert into chapter_73 (HTS_code, lft, rght, depth, title) values (73, 1, 217, 0,'Articles of iron or steel');
insert into chapter_73 (HTS_code, lft, rght, depth, title) values (73, 1, 217, 0,'Articles of iron or steel');
insert into chapter_73 (HTS_code, lft, rght, depth, title) values (73, 1, 217, 0,'Articles of iron or steel');
insert into chapter_73 (HTS_code, lft, rght, depth, title) values (73, 1, 217, 0,'Articles of iron or steel');
insert into chapter_73 (HTS_code, lft, rght, depth, title) values (73, 1, 217, 0,'Articles of iron or steel');
insert into chapter_73 (HTS_code, lft, rght, depth, title) values (73, 1, 217, 0,'Articles of iron or steel');
insert into chapter_73 (HTS_code, lft, rght, depth, title) values (73, 1, 217, 0,'Articles of iron or steel');
insert into chapter_73 (HTS_code, lft, rght, depth, title) values (73, 1, 217, 0,'Articles of iron or steel');





select * from chapter_73;