#insert into chapter_73 (HTS_code, lft, rght, depth, title) values (73, 1, 217, 0,'Articles of iron or steel');
insert into chapter_73 (HTS_code, lft, rght, depth, title) values (7307, 2, 216, 1,'Tube or pipe fittings (for example, couplings, elbows, sleeves), of iron or steel');
insert into chapter_73 (HTS_code, lft, rght, depth, title) values (7307.1, 3, 24, 2,'Cast fittings');
insert into chapter_73 (HTS_code, lft, rght, depth, title) values (7307.2, 25, 90, 2,'Other, of stainless steel');
insert into chapter_73 (HTS_code, lft, rght, depth, title) values (7307.9, 91, 215, 2,'Articles of iron or steel');
insert into chapter_73 (HTS_code, lft, rght, depth, title) values (7307.11, 4, 9, 3,'Articles of iron or steel');
insert into chapter_73 (HTS_code, lft, rght, depth, title) values (7307.19, 10, 23, 3,'Articles of iron or steel');
insert into chapter_73 (HTS_code, lft, rght, depth, title) values (7307.21, 26, 31, 3,'Articles of iron or steel');
insert into chapter_73 (HTS_code, lft, rght, depth, title) values (7307.22, 32, 45, 3,'Articles of iron or steel');
insert into chapter_73 (HTS_code, lft, rght, depth, title) values (7307.23, 46, 76, 3,'Articles of iron or steel');
insert into chapter_73 (HTS_code, lft, rght, depth, title) values (7307.29, 76, 89, 3,'Articles of iron or steel');
insert into chapter_73 (HTS_code, lft, rght, depth, title) values (7307.91, 92, 97, 3,'Articles of iron or steel');
insert into chapter_73 (HTS_code, lft, rght, depth, title) values (7307.92, 98, 111, 3,'Articles of iron or steel');
insert into chapter_73 (HTS_code, lft, rght, depth, title) values (7307.93, 112, 178, 3,'Articles of iron or steel');
insert into chapter_73 (HTS_code, lft, rght, depth, title) values (7307.99, 179, 214, 3,'Articles of iron or steel');
insert into chapter_73 (HTS_code, lft, rght, depth, title) values (7307, 1, 217, 0,'Articles of iron or steel');
insert into chapter_73 (HTS_code, lft, rght, depth, title) values (7307, 1, 217, 0,'Articles of iron or steel');
insert into chapter_73 (HTS_code, lft, rght, depth, title) values (73, 1, 217, 0,'Articles of iron or steel');
insert into chapter_73 (HTS_code, lft, rght, depth, title) values (73, 1, 217, 0,'Articles of iron or steel');
insert into chapter_73 (HTS_code, lft, rght, depth, title) values (73, 1, 217, 0,'Articles of iron or steel');
insert into chapter_73 (HTS_code, lft, rght, depth, title) values (73, 1, 217, 0,'Articles of iron or steel');
insert into chapter_73 (HTS_code, lft, rght, depth, title) values (73, 1, 217, 0,'Articles of iron or steel');
insert into chapter_73 (HTS_code, lft, rght, depth, title) values (73, 1, 217, 0,'Articles of iron or steel');
insert into chapter_73 (HTS_code, lft, rght, depth, title) values (73, 1, 217, 0,'Articles of iron or steel');
insert into chapter_73 (HTS_code, lft, rght, depth, title) values (73, 1, 217, 0,'Articles of iron or steel');
insert into chapter_73 (HTS_code, lft, rght, depth, title) values (73, 1, 217, 0,'Articles of iron or steel');
insert into chapter_73 (HTS_code, lft, rght, depth, title) values (73, 1, 217, 0,'Articles of iron or steel');
insert into chapter_73 (HTS_code, lft, rght, depth, title) values (73, 1, 217, 0,'Articles of iron or steel');
insert into chapter_73 (HTS_code, lft, rght, depth, title) values (73, 1, 217, 0,'Articles of iron or steel');
insert into chapter_73 (HTS_code, lft, rght, depth, title) values (73, 1, 217, 0,'Articles of iron or steel');
insert into chapter_73 (HTS_code, lft, rght, depth, title) values (73, 1, 217, 0,'Articles of iron or steel');
insert into chapter_73 (HTS_code, lft, rght, depth, title) values (73, 1, 217, 0,'Articles of iron or steel');
insert into chapter_73 (HTS_code, lft, rght, depth, title) values (73, 1, 217, 0,'Articles of iron or steel');
insert into chapter_73 (HTS_code, lft, rght, depth, title) values (73, 1, 217, 0,'Articles of iron or steel');
insert into chapter_73 (HTS_code, lft, rght, depth, title) values (73, 1, 217, 0,'Articles of iron or steel');
insert into chapter_73 (HTS_code, lft, rght, depth, title) values (73, 1, 217, 0,'Articles of iron or steel');
insert into chapter_73 (HTS_code, lft, rght, depth, title) values (73, 1, 217, 0,'Articles of iron or steel');
insert into chapter_73 (HTS_code, lft, rght, depth, title) values (73, 1, 217, 0,'Articles of iron or steel');
insert into chapter_73 (HTS_code, lft, rght, depth, title) values (73, 1, 217, 0,'Articles of iron or steel');
insert into chapter_73 (HTS_code, lft, rght, depth, title) values (73, 1, 217, 0,'Articles of iron or steel');
insert into chapter_73 (HTS_code, lft, rght, depth, title) values (73, 1, 217, 0,'Articles of iron or steel');
insert into chapter_73 (HTS_code, lft, rght, depth, title) values (73, 1, 217, 0,'Articles of iron or steel');
insert into chapter_73 (HTS_code, lft, rght, depth, title) values (73, 1, 217, 0,'Articles of iron or steel');
insert into chapter_73 (HTS_code, lft, rght, depth, title) values (73, 1, 217, 0,'Articles of iron or steel');
insert into chapter_73 (HTS_code, lft, rght, depth, title) values (73, 1, 217, 0,'Articles of iron or steel');
insert into chapter_73 (HTS_code, lft, rght, depth, title) values (73, 1, 217, 0,'Articles of iron or steel');
insert into chapter_73 (HTS_code, lft, rght, depth, title) values (73, 1, 217, 0,'Articles of iron or steel');
insert into chapter_73 (HTS_code, lft, rght, depth, title) values (73, 1, 217, 0,'Articles of iron or steel');
insert into chapter_73 (HTS_code, lft, rght, depth, title) values (73, 1, 217, 0,'Articles of iron or steel');
insert into chapter_73 (HTS_code, lft, rght, depth, title) values (73, 1, 217, 0,'Articles of iron or steel');
insert into chapter_73 (HTS_code, lft, rght, depth, title) values (73, 1, 217, 0,'Articles of iron or steel');
insert into chapter_73 (HTS_code, lft, rght, depth, title) values (73, 1, 217, 0,'Articles of iron or steel');
insert into chapter_73 (HTS_code, lft, rght, depth, title) values (73, 1, 217, 0,'Articles of iron or steel');
insert into chapter_73 (HTS_code, lft, rght, depth, title) values (73, 1, 217, 0,'Articles of iron or steel');
insert into chapter_73 (HTS_code, lft, rght, depth, title) values (73, 1, 217, 0,'Articles of iron or steel');
insert into chapter_73 (HTS_code, lft, rght, depth, title) values (73, 1, 217, 0,'Articles of iron or steel');
insert into chapter_73 (HTS_code, lft, rght, depth, title) values (73, 1, 217, 0,'Articles of iron or steel');
insert into chapter_73 (HTS_code, lft, rght, depth, title) values (73, 1, 217, 0,'Articles of iron or steel');
insert into chapter_73 (HTS_code, lft, rght, depth, title) values (73, 1, 217, 0,'Articles of iron or steel');
insert into chapter_73 (HTS_code, lft, rght, depth, title) values (73, 1, 217, 0,'Articles of iron or steel');
insert into chapter_73 (HTS_code, lft, rght, depth, title) values (73, 1, 217, 0,'Articles of iron or steel');
insert into chapter_73 (HTS_code, lft, rght, depth, title) values (73, 1, 217, 0,'Articles of iron or steel');
insert into chapter_73 (HTS_code, lft, rght, depth, title) values (73, 1, 217, 0,'Articles of iron or steel');
insert into chapter_73 (HTS_code, lft, rght, depth, title) values (73, 1, 217, 0,'Articles of iron or steel');





select * from chapter_73;